products/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from catalog import views

from .views import HeaterDetailView, HeaterListView, HeaterStuffListView

urlpatterns = [

    url(r'stuff/', HeaterStuffListView.as_view(), name='heater_stuff'),
    url(r'^(?P<pk>\d+)/$', HeaterDetailView.as_view(), name='heater_detail'),
    url(r'^', HeaterListView.as_view(), name='heater_list'),
    # url(r'^(?P<id>\d+)', 'products.views.product_detail_view_func', name='product_detail_view_func'),
]

# urlpatterns = patterns('',
#     url(r'^(?P<id>\d+)', 'products.views.product_detail_view_func', name='product_detail_view_func'),
# )

products/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.text import slugify


# Create your models here.
class HeaterQuerySet(models.query.QuerySet):
    def acive(self):
        return self.filter(active=True)


class HeaterManager(models.Manager):
    def get_queryset(self):
        return HeaterQuerySet(self.model, using=self._db)

    def all(self, *args, **kwargs):
        return self.get_queryset()


class Product(models.Model):
    title = models.CharField('Продукт', max_length=120)
    description = models.TextField(blank=True, null=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='обновлен')

    # slug

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.title

    # product Images

    # product Category


class Heater(models.Model):
    TYPE_CHOICES = (('lu', 'ЛУ'), ('lk', 'ЛК'))
    PANELS_CONVECTORS_CHOICES = (('10', '10'), ('11', '11'), ('20', '20'), ('21', '21'),
                                 ('22', '22'), ('30', '30'), ('33', '33'),)
    HEIGHT_CHOICES = ((300, '300 мм'), (500, '500 мм'), (600, '600 мм'), (700, '700 мм'),)
    title = models.CharField('Название', max_length=120, default='Лидея')
    heater_type = models.CharField('Тип', max_length=2, choices=TYPE_CHOICES,  default='lk',
                                   help_text='ЛК (4 боковых патрубка), ЛУ (4 боковых и 2 донных патрубка)')
    panels_convectors = models.CharField('Вид', max_length=2, choices=PANELS_CONVECTORS_CHOICES,
                                         default='22',
                                         help_text='1 цифра: кол-во панелей, 2 цифра: кол-во рядов оребрения')
    height = models.IntegerField('Высота', choices=HEIGHT_CHOICES, default=500)
    description = models.TextField('Описание', blank=True, null=True)
    price = models.DecimalField('Цена', decimal_places=2, max_digits=20)
    sale_price = models.DecimalField('Распродажная Цена', decimal_places=2, max_digits=20, null=True, blank=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='создан')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='обновлен')
    inventory = models.IntegerField('Склад', null=True, blank=True, max_length=3)  # refer none === unlimited
    work_pressure = models.DecimalField(verbose_name='Макс.раб. дав., МПа', default='1', max_digits=3, decimal_places=1)
    test_pressure = models.CharField(verbose_name='Максю дав. на прочность, МПа', default='10', max_length=2)
    max_temp_coolant = models.IntegerField(verbose_name='Макс, t\u2103', default=120)
    # connection_type
    heat_power = models.IntegerField(verbose_name='Мощность при \u0394T=70\u2103, Вт', null=True, blank=True)
    weight = models.DecimalField(verbose_name='Масса, кг', decimal_places=1, max_digits=4, null=True, blank=True)
    сapacity_liter = models.DecimalField(verbose_name='Объем, л', decimal_places=1, max_digits=4, null=True, blank=True)

    # relations
    length = models.ForeignKey('Length', verbose_name='Длина')
    product = models.ForeignKey(Product, default=1, verbose_name='Продукт')

    # manager
    objects = HeaterManager()

    # product Images
    # product Category

    class Meta:
        verbose_name = 'Радиатор'
        verbose_name_plural = 'Радиаторы'

    def __str__(self):
            return '%s, %s, %s-%s, %sx%s' % (
                self.product,
                self.title,
                self.get_heater_type_display(),
                self.panels_convectors,
                self.height,
                self.length
            )

    def get_absolute_url(self):
        return reverse("heater_detail", kwargs={"pk": self.pk})

    def get_price(self):
        if self.sale_price is not None:
            return self.sale_price
        else:
            return self.price


class Length(models.Model):
    LENGTH_CHOICES = (
        (400, '400 мм'), (500, '500 мм'), (600, '600 мм'), (700, '700 мм'), (800, '800 мм'),
        (900, '900 мм'), (1000, '1000 мм'), (1100, '1100 мм'), (1200, '1200 мм'), (1300, '1300 мм'),
        (1400, '1400 мм'), (1500, '1500 мм'), (1600, '1600 мм'), (1700, '1700 мм'), (1800, '1800 мм'),
        (1900, '1900 мм'), (2000, '2000 мм'), (2100, '2100 мм'), (2200, '2200 мм'), (2300, '2300 мм'),
        (2400, '2400 мм'), (2500, '2500 мм'), (2600, '2600 мм'), (2700, '2700 мм'), (2800, '2800 мм'),
        (2900, '2900 мм'), (3000, '3000 мм'),
    )
    length = models.IntegerField('Длина радиатора', choices=LENGTH_CHOICES, unique=True)

    class Meta:
        verbose_name = 'Длина радиатора'
        verbose_name_plural = 'Длины радиаторов'
        # unique_together = ('length',)

    def __str__(self):
        return self.get_length_display()


def image_upload_to(instance, filename):
    slug = slugify("%s%s%sx%s" % (instance.heater.heater_type, instance.heater.panels_convectors, instance.heater.height, instance.heater.length))
    return "products/%s/%s" % (slug, filename)


class HeaterImage(models.Model):
    heater = models.ForeignKey(Heater)
    image = models.ImageField(upload_to=image_upload_to)

    def __str__(self):
        return self.heater.title

products/forms.py
from django import forms
from django.forms.models import modelformset_factory

from .models import Heater
from crispy_forms.layout import Layout
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import PrependedText, Field


class HeaterStuffForm(forms.ModelForm):
    class Meta:
        model = Heater
        fields = [
            "price",
            "sale_price",
            "inventory",
            "active",
        ]

    def __init__(self, *args, **kwargs):
        super(HeaterStuffForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        # self.helper.field_template = 'bootstrap3/layout/inline_field.html'
        self.helper.field_class = 'small-input'
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Field("price", css_class="price"),
            Field("sale_price", css_class="sale_pricep"),
            Field("inventory", css_class="inventory"),
            Field("active", css_class="checkbox"),
        )
        super(HeaterStuffForm, self).__init__(*args, **kwargs)
HeaterStuffFormSet = modelformset_factory(Heater, form=HeaterStuffForm, extra=0)

products/views.py
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.utils import timezone
from django.contrib import messages
from braces import views
from pprint import pprint
# Create your views here.


from .models import Product, Heater

from .forms import HeaterStuffFormSet


class HeaterListView(ListView):
    model = Heater
    queryset = Heater.objects.all()
    # template_name = "<appname>/<modelname>_detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(HeaterListView, self).get_context_data(*args, **kwargs)
        context["now"] = timezone.now()
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(HeaterListView, self).get_queryset(*args, **kwargs).filter(active=True)
        query = self.request.GET.get("q")
        if query:
            qs = self.model.objects.filter(
                Q(description__icontains=query) |
                Q(title__icontains=query)
            )
        return qs


class HeaterStuffListView(views.LoginRequiredMixin, views.StaffuserRequiredMixin, ListView):
    model = Heater
    queryset = Heater.objects.all()
    template_name = 'products/heater_stuff_list.html'

    def get_context_data(self, *args, **kwargs):
        context = super(HeaterStuffListView, self).get_context_data(*args, **kwargs)
        context["formset"] = HeaterStuffFormSet(queryset=self.get_queryset())
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(HeaterStuffListView, self).get_queryset(*args, **kwargs)
        query = self.request.GET.get("q")
        if query:
            qs = self.model.objects.filter(
                Q(description__icontains=query) |
                Q(title__icontains=query)
            )
        return qs

    def post(self, request, *args, **kwargs):
        formset = HeaterStuffFormSet(request.POST, request.FILES)
        if formset.is_valid():
            formset.save(commit=False)
            for form in formset:
                form.save()
            messages.success(request, "Список обновлен")
            return redirect("heater_stuff")
        raise Http404


class HeaterDetailView(DetailView):
    model = Heater
    # template_name = "<appname>/<modelname>_detail.html"


def product_detail_view_func(request, id):
    # product_instance = Product.objects.get(id=id)
    product_instance = get_object_or_404(Product, id=id)

    template = "products/heater_detail.html"
    context = {
        "object": product_instance
    }
    return render(request, template, context)

products/templates/products/heater_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3 left side">
            <p>left side. Here some filter must be</p>
        </div>
        <div class="col-md-6 center side">
        <h3>{{ object }}</h3>
            {% if object.heaterimage_set.count > 0 %}
                <div>
                {% for img in object.heaterimage_set.all %}
                    <img class="img-responsive center-block" src="{{ img.image.url }}">
                {% endfor %}
                </div>
            {% endif %}
            <hr>
            <p class="lead">Описание</p>
            {{ object.description }}
            <hr>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th class="text-center lead" colspan="2">Характеристики</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Высота:</td>
                    <td>{{ object.height }} мм</td>
                </tr>
                <tr>
                    <td>Длина:</td>
                    <td>{{ object.length }}</td>
                </tr>
                <tr>
                    <td>Тепловая мощность при ΔT=70℃</td>
                    <td>{{ object.heat_power }} Вт</td>
                </tr>
                <tr>
                    <td>Вес</td>
                    <td>{{ object.weight }} кг</td>
                </tr>
                <tr>
                    <td>Рабочее давление:</td>
                    <td>до {{ object.work_pressure }} ATM</td>
                </tr>
                <tr>
                    <td>Испытательное давление:</td>
                    <td>{{ object.test_pressure }} ATM</td>
                </tr>
                <tr>
                    <td>Макс. температура теплоносителя:</td>
                    <td>{{ object.max_temp_coolant }}°C</td>
                </tr>
                <tr>
                    <td>Шаг вертикальных водоканалов:</td>
                    <td>33,3 мм</td>
                </tr>
                <tr>
                    <td>Цвет покрытия:</td>
                    <td>Белый (RAL 9016)</td>
                </tr>
                <tr>
                    <td>Стандарт присоединения:</td>
                    <td>{% if object.heater_type == 'lk' %}
                        «Лидея Компакт» - 4 присоединительных патрубка с внутренней резьбой G 1/2
                    {% else %}
                        «Лидея Универсал» - 4 боковых и 2 нижних присоединительных патрубка с внутренней резьбой G 1/2.
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td>Материал панели</td>
                    <td>Сталь холодного проката, соответствует
                        EN 10131, толщина 1,2 мм
                    </td>
                </tr>
                <tr>
                    <td>Материал конвектора</td>
                    <td>Сталь холодного проката, соответствует
                        EN 10131, толщина 0,4 мм
                    </td>
                </tr>
                <tr>
                    <td colspan="2">Обработка поверхности:
                        обезжиривание, травление, фосфатирование, пассивация, погружение в водорастовримый грунт,
                        нанесение
                        порошковой эмали методом пневмоэлектрического напыления, обжиг при температуре 200-220 °С
                        соответствует DIN 55 900.
                    </td>
                </tr>
                <tr>
                    <td>Гарантия</td>
                    <td>5 лет</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-3 right side">
            <p>right side</p>
            {% if object.sale_price %}
                <p><i class="fa fa-tag fa-lg sale-price"> {{ object.sale_price }} грн</i> </p>
                <p class="lead"><i class="fa fa-money price"></i> {{ object.price }} грн</p>
                {% else %}
                <p class="lead"><i class="fa fa-money price"></i> {{ object.price }} грн</p>
            {% endif %}
            <a class="btn btn-primary btn-block" href="#"><i class="fa fa-shopping-basket"></i> Добавить в корзину</a>
        </div>
    </div>
{% endblock %}

products/templates/products/heater_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-3 left side">
            <div class="row">
                <form class="navbar-form" role="search">
                    <div class="input-group add-on">
                        <input type="text" class="form-control" method="GET" action="{% url "heater_list" %}"
                               placeholder="Поиск..." name="q" id="srch-term">

                        <div class="input-group-btn">
                            <button class="btn btn-primary btn-block" type="submit"><i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-9 center side">
            <table class="table table-hover table-bordered">
                {% for object in object_list %}
                    <tr>
                        {#        <td>#}
                        {#            <a href="{% url 'heater_detail' pk=object.pk %}">{{ object }} {{ object.length }} {{ object.heater_type }}</a>#}
                        {#        </td>#}
                        <td>
                            <a href="{{ object.get_absolute_url }}">{{ object }}</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

products/templates/products/heater_stuff_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}


{% block content %}
    <div class="row">
        <div class="col-md-3 left side">
            <div class="row">
                <form class="navbar-form" role="search">
                    <div class="input-group add-on">
                        <input type="text" class="form-control" method="GET" action="{% url "heater_stuff" %}"
                               placeholder="Поиск..." name="q">

                        <div class="input-group-btn">
                            <button class="btn btn-primary btn-block" type="submit"><i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-7 center side">
            <div class="row">
                <div class="col-md-12">
                    <form method="POST" action={% url "heater_stuff" %}> {% csrf_token %}
                        {{ formset.management_form }}
                        <table class="table-bordered col-md-12">
                            <thead>
                            <tr>
                                <th class="col-md-5">Наименование</th>
                                <th class="col-md-7" colspan="4">
                                    <text style="white-space: pre;"> Цена прод. | Цена скидк.   | Склад | Активно</text>
                                </th>
                            </tr>
                            </thead>
                            {% for form in formset %}
                                <tr>
                                    <td class="col-md-5">
                                        <a href="{{ form.instance.get_absolute_url }}">{{ form.instance }}</a>
                                    </td>
                                    <td class="col-md-7">
                                        {% for field in form.visible_fields %}
                                            {{ field }}
                                        {% endfor %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                        <input class="btn btn-primary btn-lg pull-right" type="submit" value="Обновить">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}